name = input("enter name of the student:")
mobile_no = input("enter mobile number:")
mail_id = input ("enter mail id of the student:")
college = input("enter the name of the college:")
branch = input("enter branch")
print (".........Student Profile.........")
print("*************************************************************")
print ("nameof the student is" + name)
print ("the mobile no is" + mobile_no)
print ("the mail id"+ mail_id)
print ("college is"+ college)
print ("brach is" +branch) 
